#In DAY 2, Learn About Data Types in Python

#Numerics
num_int = 1
num_float = 1.5
num_long = 65665959592929292
num_complex = 100+3j

#String Data Type
str = "HEllo, This is String"


#List Data Type
list_list = [1, "bb", True]
list_tuples = ("Hey", "This", "is", "tuples")
list_range = range(6)

#Mapping Data Type
map_dict = {1:"baby", 2:"18"}

#set Data Type
set_set = {"this", "is", "set"}
set_frozenset = frozenset({"this", "is", "frozenset"})

#Boleen Data Type
bool_boolen = False

# LETS PRINT OUT DATA TYPR

print("THIS IS ALL NUMERICAL DATA TYPE")
print("This is Integer ", num_int)
print("This is Float ", num_float)
print("This is Long Interger", num_long)
print("This is Complex", num_complex)
